
services:
    postgres:
      container_name: postgres
      image: postgres
      environment: 
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: stem_diverse_tv
      ports:
        - 5432:5432
    stem_diverse_tv: 
      container_name: stem_diverse_tv
      build: .  
      ports: 
        - 5000:5000
      depends_on:
        - postgres 
        

