name: Lint code & Run tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
  
  build:
    needs: lint
    runs-on: Ubuntu-20.04

    env:
      DB_TYPE: postgresql
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_ENDPOINT: localhost:5432 
      DB_TEST_NAME: stem_diverse_test
      
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Connect to PostgreSQL
      run: |
        PGPASSWORD=postgres psql -h localhost -c 'CREATE DATABASE stem_diverse_test;' -U postgres
      env:
        POSTGRES_HOST: localhost
    
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover tests -v
